# Generated by Django 5.0.6 on 2025-03-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrainTumorAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('symptoms', models.TextField()),
                ('duration', models.IntegerField()),
                ('conditions', models.TextField(blank=True, null=True)),
                ('conditions_image', models.ImageField(blank=True, null=True, upload_to='conditions_images/')),
                ('previous_diagnosis', models.TextField(blank=True, null=True)),
                ('diagnosis_image', models.ImageField(blank=True, null=True, upload_to='diagnosis_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
